### ISSUE TITLE
eslint-config-pebblecode not loading in local project

### ISSUE THREAD

**Issue by tanepiper** [pebblecode/node-starter-kit#5]
With Webstorm, using eslint internally I was getting errors that it could not find `eslint-config-pebblecode`.

Had to install it globally with eslint to get it work.  Is there a way we can resolve this sensibly?

**Comment by tanepiper** [comment]
Also, looks like there is a dependency on `eslint-plugin-react`:

```
/usr/local/bin/node /usr/local/lib/node_modules/eslint/bin/eslint.js --format=checkstyle --stdin --stdin-filename server/index.js
Cannot find module 'eslint-plugin-react'
Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:124:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:115:21)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:202:5)
    at CLIEngine.executeOnText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:678:26)
    at Object.cli.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:161:36)
```

This is a non-react project

**Comment by export-mike** [comment]
I think you need to get your webstorm to look at the working dir `node_modules/.bin`

**Comment by export-mike** [comment]
or get webstorm to run the command `npm run lint` instead?
